---
title: "hw6"
author: "Ruihan Zhang"
date: "2022-11-30"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(viridis)
library(dplyr)
library(purrr)
library(broom)
library(plotly)
library(modelr)
library(mgcv)

set.seed(1)

```

```{r}
homicide= read_csv("./data/homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(city_state = str_c(city,", ",state)) %>% 
  mutate(outcome = case_when(disposition == "Closed without arrest" ~ 'not solved',
                           disposition == 'Closed by arrest' ~ 'solved',
                           disposition == "Open/No arrest" ~ 'not solved')
  ) %>% 
  filter(city_state != "Dallas, TX",
         city_state != "Phoenix, AZ",
         city_state != "Kansas City, MO",
         city_state != "Tulsa, AL",
         ) %>% 
  filter(victim_race == "White" | victim_race == "Black") %>% 
  mutate(., victim_age = as.numeric(victim_age))
```

```{r}
Baltimore = homicide %>% 
  filter(city_state == "Baltimore, MD") %>% 
  mutate(outcome = case_when(outcome ==  'not solved' ~ "0",
                           outcome ==  'solved' ~ "1")) %>% 
  mutate(outcome = as.numeric(outcome))
  
```

```{r}
sink("fit.txt")
 fit = glm(formula = outcome~victim_race+victim_age+victim_sex, family = binomial(), data = Baltimore)
 print(fit)
 sink()
```


```{r}
mf = fit %>%  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    lower_ci = exp(estimate - 1.96 * std.error),
    upper_ci = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, estimate, OR, lower_ci,upper_ci ) %>% 
  knitr::kable(digits = 3)

mf
```




```{r}
city_nest = homicide %>% 
  select(city_state, victim_race, victim_age, victim_sex, outcome) %>% 
  mutate(outcome = case_when(outcome ==  'not solved' ~ "0",
                           outcome ==  'solved' ~ "1")) %>% 
  mutate(outcome = as.numeric(outcome)) %>% 
  nest(data = victim_race:outcome)
```

```{r}
city_nest %>% pull(data)
```

```{r}
city = unnest(city_nest, cols = data)
```

```{r}

glm_function = function(x)
   { glm(formula = outcome~victim_race+victim_age+victim_sex, family = binomial(), data = x) %>%  broom::tidy() %>%  
    tibble(OR = exp(estimate), lower_ci = exp(estimate - 1.96 * std.error),upper_ci = exp(estimate + 1.96 * std.error)) %>% 
    select(term, estimate, OR, lower_ci,upper_ci ) 
      
}
```

```{r}
nest_city = city_nest %>% 
  mutate(models = map(data, glm_function)) %>% 
  unnest(models)
```

```{r}
city_fm = nest_city %>% 
  select(city_state,term,OR, lower_ci,upper_ci) %>% 
  filter(term == "victim_sexMale") 
```

```{r}
city_plot=city_fm %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  
  ggplot(aes(x = city_state, y = OR))+
  geom_point()+
  geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci))+
  labs(title = "odds ratio and confidence intervals for each city", 
       y = "odds ratio", 
       x = "city_state ")+theme(axis.text.x = element_text(angle = 90, vjust = 0.2, hjust = 1))
city_plot               
  
```

```{r}
birthweight = read_csv("./data/birthweight.csv") %>% 
  janitor::clean_names() %>% 
  na.omit() %>% 
  mutate(babysex = as.factor(babysex),
         frace = as.factor(frace),
         malform = as.factor(malform),
         mrace = as.factor(mrace))
```
New York has the lowest odds ratio, and Albuquerque has the highest odd ratio.The odds ratio of most cities are below 1, which means that compared to homicide cases of female, that of male victims has smaller odds ratio of being solved. Overall, there are more unsolved homicide cases associated with males than females.
```{r}
fit1 = lm(bwt ~  smoken + fincome + wtgain, data = birthweight) 
```
```{r}
birthweight_plot = birthweight %>% 
  add_predictions(fit1) %>% 
  add_residuals(fit1) %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point(alpha = .5)
birthweight_plot
```



```{r}
fit2 = lm(bwt ~ blength + gaweeks, data = birthweight)
fit3 = lm(bwt ~ bhead + blength + babysex + bhead*blength*babysex, data = birthweight)
```

```{r}
compare =
  crossv_mc(birthweight, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

```{r}
compare = 
  compare %>% 
  mutate(
    fit1  = map(train, ~lm(bwt ~  smoken + fincome + wtgain, data = .x)),
    fit2     = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    fit3  = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength*babysex, data =.x))) %>% 
  mutate(
    rmse_model1 = map2_dbl(fit1, test, ~rmse(model = .x, data = .y)),
    rmse_model2    = map2_dbl(fit2, test, ~rmse(model = .x, data = .y)),
    rmse_model3 = map2_dbl(fit3, test, ~rmse(model = .x, data = .y)))
```

```{r}
compare_plot=  compare%>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
compare_plot
```

